In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('center.csv')

In [3]:
['']

          name     sup  NChild  ETHSchool  Chores  mobile  laptop  sib
0        یاسین  father       1          4       2       0       0    0
1       علیرضا  father       2          3       3       1       0    1
2     محمدجواد  mother       1          3       3       1       0    0
3         مهدی    both       1          5       3       1       0    1
4        بردیا  father       1          4       3       0       1    1
5      امیرسام    both       1          1       2       1       0    0
6    امیرعلی پ    both       2          4       5       0       1    1
7     محمدحسین    both       2          5       3       1       0    1
8        اهورا  father       2          3       4       1       1    1
9         آرین  father       1          2       3       1       0    1
10       سبحان    both       2          5       4       0       1    1
11     بنیامین  father       2          3       4       0       0    1
12        صالح   other       2          3       4       0       0    1
13      مهریاد    both       1          4       3       0       0    0
14   امیرعلی خ  mother       2          5       5       0       0    1
15    علیرضا د  mother       2          3       4       0       0    1
16     امیررضا    both       2          4       5       0       1    1
17        کسری    both       2          3       5       0       1    1
18      همایون  mother       1          4       2       1       1    0
19    امیرحسام    both       2          5       5       1       0    1
20   بنیامین ز  mother       1          5       3       0       0    1
21    محمدحسام  mother       1          3       3       1       0    0
22    محمدمهدی  father       1          3       3       1       0    0
23    محمدامین    both       2          5       3       0       1    1
24    ابوالفضل    both       1          5       5       0       0    1
25        حسام    both       1          5       4       1       0    1
26    امیرحسین    both       2          5       4       1       1    1
27   امیرعلی ص  father       2          4       5       1       0    1
28   امیررضا ص  father       3          5       5       0       0    1
29       مهراد  mother       1          3       3       0       0    0
30  محمدمهدی ک  mother       1          5       4       0       1    1
31     امیرعلی  father       3          4       4       0       1    1
32      کامیار  father       2          3       3       0       0    1
33     سیدمبین    both       2          3       3       0       0    1
34      مهرزار    both       2          4       2       1       0    1
35      مهرسام    both       1          3       4       0       1    0